### PR TITLE
"Port" HSF from the main app.

### PR DESCRIPTION
**Pull request by RamesTheGeneric**
This is what I have so far for the HSF algo. I'd appreciate it if someone will review.

Currently I'm dividing the output coordinates by an arbitrary amount to get a value that will fit in the osc output preview. I'm unsure if HSF in the main app outputs normalized coordinates like leap or if raw pixel coordinates are dealt with in the calibration step. If it is dealt with in the calibration step, this division can probably be removed. 

As for blinking, I was told HSF does have some kind of blink metric but I couldn't find any use of it in the main app or a blink value in the algo file. 

Commented code lines and standalone run functionality was removed.

- Implements the HSF algo for gaze.

### CODE REVIEW

**Comment by ShyAssassin** [comment]
LGTM!
Will do a proper review and merge it later today

**Comment by ShyAssassin** [comment]
For some reason the CI/CD didn't automatically run on this PR

Can you please run `python build.py lint` locally and fix any problems that may arise?

**Comment by RamesTheGeneric** [comment]
Any problems lint returned for HSF appears to have been resolved locally now.

**Comment by ShyAssassin** [comment]
Everything looks good and works as expected, i will merge it when i get home!
But before we create a new release from `feature/algorithms` we should cleanup HSF, here are a the main things we should do

* Add type hinting to methods and variables
* Add debugging logging with `ep.logger.*()`
* Combine all HSF related methods into the main `HSF` class and remove the external run method
* Create a `dataclass` or `BaseModel` to hold configuration variables

**Pull request merged**
